# Site settings
title: Testing LiteMap
email: labs@ouishare.net
description: > # this means to ignore newlines until "baseurl:"
  OuiShare and LiteMap test. Project report
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://litemap.ouisharelabs.net" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

gaid: UA-868449-9